#!/usr/bin/env python3
"""
M5 — Frida Hook Generator

Generate real Frida JavaScript instrumentation hooks from a JSON specification:

  * Java hooks  — Java.perform { Java.use(...).<method>.implementation = ... }
  * Native hooks — Interceptor.attach(...) on exported symbols / module bases
  * Combined   — an on-load script that retrieves a class/the loaded module.

The generator is fully OFFLINE and stdlib-only. No frida device is needed to
generate or validate; the JS is validated with a built-in structural validator
(no node required).

WARNING: For authorized device-owner / lab use only. Only hook applications
you own or have explicit permission to instrument.

Usage:
    python3 frida_gen.py generate spec.json -o out/
    python3 frida_gen.py validate script.js
    python3 frida_gen.py demo                      # offline demo, exits 0
"""

import argparse
import json
import os
import re
import sys


# ---------------------------------------------------------------------------
# spec model
# ---------------------------------------------------------------------------

DEFAULT_SPEC = {
    "package": "com.lab.app",
    "hooks": [
        {
            "type": "java",
            "class": "com.lab.app.core.AuthManager",
            "method": "login",
            "params": ["java.lang.String", "java.lang.String"],
            "return": "boolean",
            "on_enter": {
                "log_args": True,
                "annotate": "AUTH-LOGIN"
            }
        },
        {
            "type": "java",
            "class": "com.lab.app.core.CryptoBox",
            "method": "decrypt",
            "params": ["[B"],
            "return": "[B",
            "on_exit": {}
        },
        {
            "type": "native",
            "module": "libnative.so",
            "symbol": "crypto_box_decrypt",
            "on_enter": {"log": "NATIVE-CRYPTO enter"}
        }
    ]
}


class SpecError(Exception):
    pass


def validate_spec(spec):
    """Structural validation of the hook spec dict. Returns list of errors."""
    errors = []
    if not isinstance(spec, dict):
        return ["spec must be a JSON object"]
    if not isinstance(spec.get("package"), str):
        errors.append("'package' must be a string")
    hooks = spec.get("hooks")
    if not isinstance(hooks, list) or not hooks:
        errors.append("'hooks' must be a non-empty array")
        return errors
    for i, h in enumerate(hooks):
        if not isinstance(h, dict):
            errors.append("hooks[%d] must be an object" % i)
            continue
        t = h.get("type")
        if t not in ("java", "native"):
            errors.append("hooks[%d].type must be 'java' or 'native' (got %r)"
                          % (i, t))
        if t == "java":
            if not isinstance(h.get("class"), str) or not h["class"]:
                errors.append("hooks[%d].class required for java hook" % i)
            if not isinstance(h.get("method"), str) or not h["method"]:
                errors.append("hooks[%d].method required for java hook" % i)
            params = h.get("params")
            if params is not None and not isinstance(params, list):
                errors.append("hooks[%d].params must be a list" % i)
        elif t == "native":
            if not isinstance(h.get("module"), str) or not h["module"]:
                errors.append("hooks[%d].module required for native hook" % i)
            if not isinstance(h.get("symbol"), str) or not h["symbol"]:
                errors.append("hooks[%d].symbol required for native hook" % i)
    return errors


# ---------------------------------------------------------------------------
# JS generation
# ---------------------------------------------------------------------------

JS_TEMPLATE = """\
/* Auto-generated by m5-frida-gen — authorized lab instrumentation */
'use strict';

var PKG = "%(package)s";

function logEvent(tag, msg) {
  if (typeof send === 'function') {
    send({ tag: tag, message: String(msg) });
  } else {
    console.log('[' + tag + '] ' + String(msg));
  }
}

%(java_body)s

%(native_body)s

function main() {
  if (typeof Java !== 'undefined' && Java.available) {
    Java.perform(function () {
      %(java_init)s
    });
  }
  if (typeof Module !== 'undefined' && typeof Interceptor !== 'undefined') {
    %(native_init)s
  }
  logEvent('init', 'hooks installed for ' + PKG);
}

main();
"""


def _js_string(value):
    """Literal double-quoted JS string from a python value."""
    s = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return '"%s"' % s


def gen_java_hook(h, idx):
    """Produce a JS statement block that overrides a Java method."""
    cls = h["class"]
    method = h["method"]
    params = h.get("params") or []
    params = ["'%s'" % p for p in params] if params else []
    arglist = ", ".join(params)
    on_enter = h.get("on_enter") or {}
    on_exit = h.get("on_exit") or {}

    # overload selection when parameters are specified
    overload_call = ""
    if arglist:
        overload_call = ".overload(%s)" % arglist

    log_enter = ""
    if on_enter.get("log_args"):
        tag = on_enter.get("annotate") or ("HOOK-%d" % idx)
        args_join = "Array.prototype.slice.call(arguments).join(', ')"
        log_enter = ("      logEvent(%s, 'enter args: ' + (%s));"
                     % (_js_string(tag), args_join))

    ret_log = ""
    if "return" in on_exit:
        tag = on_exit.get("annotate") or ("HOOK-%d" % idx)
        ret_log = ("      logEvent(%s, String(this.returnValue));"
                   % (_js_string(tag)))

    sig = "%s.%s%s" % (cls, method, overload_call)
    block = ("    var inst = Java.use(%s);\n"
             "    if (inst) {\n"
             "      var target = inst.%s%s;\n"
             "      if (typeof target === 'function') {\n"
             "        target.implementation = function () {\n"
             "%s"
             "          var ret = this.%s.apply(this, arguments);\n"
             "%s"
             "          return ret;\n"
             "        };\n"
             "      } else {\n"
             "        logEvent(%s, 'method not found: ' + %s);\n"
             "      }\n"
             "    } else {\n"
             "      logEvent(%s, 'class not found: ' + %s);\n"
             "    }"
             % (_js_string(cls), method, overload_call, log_enter, method,
                ret_log, _js_string("hook-miss"),
                _js_string("%s.%s" % (cls, method)),
                _js_string("hook-miss"), _js_string(cls))
             )
    return block, sig


def gen_native_hook(h, idx):
    module = h["module"]
    symbol = h["symbol"]
    on_enter = h.get("on_enter") or {}
    on_exit = h.get("on_exit") or {}

    enter_log = ""
    if on_enter.get("log"):
        enter_log = ("      logEvent(%s, 'enter: ' + %s);\n"
                     % (_js_string(on_enter["log"]), _js_string(symbol)))

    exit_log = ""
    if on_exit.get("log_return"):
        exit_log = ("      logEvent(%s, 'exit: ' + retval);\n"
                    % (_js_string(on_exit["log_return"])))

    block = ("    var base = Module.findBaseAddress(%s);\n"
             "    if (base) {\n"
             "      var addr = Module.findExportByName(%s, %s);\n"
             "      if (addr) {\n"
             "        Interceptor.attach(addr, {\n"
             "          onEnter: function (args) {\n"
             "%s"
             "          },\n"
             "          onLeave: function (retval) {\n"
             "%s"
             "          }\n"
             "        });\n"
             "      } else {\n"
             "        logEvent('hook-miss', 'export not found: ' + %s);\n"
             "      }\n"
             "    }"
             % (_js_string(module), _js_string(symbol), _js_string(symbol),
                enter_log, exit_log, _js_string(symbol))
             )
    return block


def generate(spec, package=None):
    errors = validate_spec(spec)
    if errors:
        raise SpecError("; ".join(errors))
    pkg = package or spec.get("package") or "com.lab.app"

    java_blocks, native_blocks = [], []
    java_sigs = []
    for i, h in enumerate(spec["hooks"]):
        if h["type"] == "java":
            block, sig = gen_java_hook(h, i)
            java_blocks.append(block)
            java_sigs.append(sig)
        else:
            native_blocks.append(gen_native_hook(h, i))

    java_init = "\n      ".join(";".join(
        "try { " + b.replace("\n", " ").strip() + " } catch (e) { "
        "logEvent('java-error', e); }" for b in java_blocks)) if java_blocks \
        else "logEvent('init', 'no java hooks');"

    native_init = "\n      ".join(";".join(
        "try { " + b.replace("\n", " ").strip() + " } catch (e2) { "
        "logEvent('native-error', e2); }" for b in native_blocks)) \
        if native_blocks else "logEvent('init', 'no native hooks');"

    script = JS_TEMPLATE % {
        "package": pkg,
        "java_body": "\n\n".join(java_blocks),
        "native_body": "\n\n".join(native_blocks),
        "java_init": java_init,
        "native_init": native_init,
    }
    return script, {"java_signatures": java_sigs}


# ---------------------------------------------------------------------------
# offline JS structural validator (no node required)
# ---------------------------------------------------------------------------

# simple delimiters that must be balanced; these are disjoint in the
# generated code (strings are double-quoted and do not contain { }).
_OPENS = {"(": ")", "[": "]", "{": "}"}
_PAIRS = {"(": ")", "[": "]", "{": "}"}


def validate_js(src):
    """Structural validation: balanced (), [], {} outside of single- or
    double-quoted strings and line/block comments. Returns (ok, error_or_None)."""
    stack = []
    i = 0
    n = len(src)
    while i < n:
        c = src[i]
        if c == '"' or c == "'":           # string literal
            quote = c
            i += 1
            while i < n:
                if src[i] == "\\":
                    i += 2
                    continue
                if src[i] == quote:
                    break
                i += 1
            i += 1
            continue
        if c == "/" and i + 1 < n and src[i + 1] == "/":   # line comment
            i = src.find("\n", i)
            if i == -1:
                break
            continue
        if c == "/" and i + 1 < n and src[i + 1] == "*":   # block comment
            j = src.find("*/", i + 2)
            if j == -1:
                return False, "unterminated block comment"
            i = j + 2
            continue
        if c in _OPENS:
            stack.append(c)
        elif c in _PAIRS.values():
            if not stack:
                return False, "unbalanced closing '%s' at offset %d" % (c, i)
            if _PAIRS[stack[-1]] != c:
                return False, "mismatched '%s' (expected %s) at offset %d" % (
                    c, _PAIRS[stack[-1]], i)
            stack.pop()
        i += 1
    if stack:
        return False, "unbalanced opening '%s'" % _PAIRS[stack[-1]]
    return True, None


# ---------------------------------------------------------------------------
# declarative analysis / validation niceties
# ---------------------------------------------------------------------------


def print_generated(script, info, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    script_path = os.path.join(out_dir, "script.js")
    with open(script_path, "w") as f:
        f.write(script)
    info_path = os.path.join(out_dir, "metadata.json")
    with open(info_path, "w") as f:
        json.dump(info, f, indent=2)
    return script_path, info_path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def demo():
    print("=" * 66)
    print("  M5 - Frida Hook Generator - offline demo")
    print("=" * 66)
    script, info = generate(DEFAULT_SPEC)
    ok, err = validate_js(script)
    print("  Generated script (%d bytes)" % len(script))
    print("  Java hooks: %d  Native hooks: %d"
          % (len(info["java_signatures"]),
             script.count("Interceptor.attach")))
    print("  JS structural validation: %s" % ("OK" if ok else "FAIL: " + str(err)))
    print("  Java signatures:")
    for s in info["java_signatures"]:
        print("    - %s" % s)
    print("  Native hooks:")
    for line in script.splitlines():
        if "Interceptor.attach" in line:
            print("    - " + line.strip()[:60])
    print("exit=0")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="frida_gen.py",
        description="M5 - Frida Hook Generator (JSON spec -> real Java + "
                    "native hooks; offline JS validator)")
    sub = parser.add_subparsers(dest="cmd")

    p_gen = sub.add_parser("generate", help="generate script.js from a spec")
    p_gen.add_argument("spec", help="path to JSON hook spec")
    p_gen.add_argument("-o", "--output", default=None,
                       help="output dir (default reports/)")
    p_gen.add_argument("--validate", action="store_true",
                       help="run structural JS validation after generation")

    p_val = sub.add_parser("validate", help="validate a JS file structurally")
    p_val.add_argument("script", help="path to JS file")

    p_demo = sub.add_parser("demo", help="offline demo (exits 0)")
    args = parser.parse_args(argv)

    if args.cmd == "demo":
        return demo()

    if args.cmd == "validate":
        if not os.path.exists(args.script):
            print("Error: file not found: %s" % args.script)
            return 1
        with open(args.script) as f:
            src = f.read()
        ok, err = validate_js(src)
        print("JS structural validation: %s" % ("OK" if ok else "FAIL"))
        if not ok:
            print("  error: %s" % err)
            return 1
        return 0

    if args.cmd == "generate":
        if not os.path.exists(args.spec):
            print("Error: spec not found: %s" % args.spec)
            return 1
        try:
            with open(args.spec) as f:
                spec = json.load(f)
            script, info = generate(spec)
        except SpecError as e:
            print("Spec error: %s" % e)
            return 1
        except json.JSONDecodeError as e:
            print("Invalid JSON spec: %s" % e)
            return 1
        out = args.output or os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "reports", "frida")
        script_path, info_path = print_generated(script, info, out)
        print("Wrote %s" % script_path)
        print("Wrote %s" % info_path)
        if args.validate or True:
            ok, err = validate_js(script)
            print("JS structural validation: %s"
                  % ("OK" if ok else "FAIL: " + str(err)))
            if not ok:
                return 1
        return 0

    parser.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())